# TCL File Generated by Component Editor 14.1
# Thu Jan 28 17:59:43 CET 2016
# DO NOT MODIFY


# 
# clusterip "clusterip" v1.0
#  2016.01.28.17:59:43
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module clusterip
# 
set_module_property DESCRIPTION ""
set_module_property NAME clusterip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME clusterip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL clusterip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file clusterip.sv SYSTEM_VERILOG PATH clusterip.sv TOP_LEVEL_FILE
add_fileset_file K2000.sv SYSTEM_VERILOG PATH K2000.sv
add_fileset_file gene_clk.sv SYSTEM_VERILOG PATH gene_clk.sv
add_fileset_file SEG7_LUT.sv SYSTEM_VERILOG PATH SEG7_LUT.v
add_fileset_file SEG7_LUT_8.sv SYSTEM_VERILOG PATH SEG7_LUT_8.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL clusterip
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file clusterip.sv SYSTEM_VERILOG PATH clusterip.sv
add_fileset_file K2000.sv SYSTEM_VERILOG PATH K2000.sv
add_fileset_file gene_clk.sv SYSTEM_VERILOG PATH gene_clk.sv
add_fileset_file SEG7_LUT.sv SYSTEM_VERILOG PATH SEG7_LUT.v
add_fileset_file SEG7_LUT_8.sv SYSTEM_VERILOG PATH SEG7_LUT_8.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point leds
# 
add_interface leds conduit end
set_interface_property leds associatedClock ""
set_interface_property leds associatedReset ""
set_interface_property leds ENABLED true
set_interface_property leds EXPORT_OF ""
set_interface_property leds PORT_NAME_MAP ""
set_interface_property leds CMSIS_SVD_VARIABLES ""
set_interface_property leds SVD_ADDRESS_GROUP ""

add_interface_port leds leds leds Output 10


# 
# connection point hex
# 
add_interface hex conduit end
set_interface_property hex associatedClock clock
set_interface_property hex associatedReset ""
set_interface_property hex ENABLED true
set_interface_property hex EXPORT_OF ""
set_interface_property hex PORT_NAME_MAP ""
set_interface_property hex CMSIS_SVD_VARIABLES ""
set_interface_property hex SVD_ADDRESS_GROUP ""

add_interface_port hex HEX1 hex1 Output 7
add_interface_port hex HEX2 hex2 Output 7
add_interface_port hex HEX3 hex3 Output 7
add_interface_port hex HEX4 hex4 Output 7
add_interface_port hex HEX5 hex5 Output 7
add_interface_port hex HEX0 hex0 Output 7


# 
# connection point SW
# 
add_interface SW conduit end
set_interface_property SW associatedClock clock
set_interface_property SW associatedReset ""
set_interface_property SW ENABLED true
set_interface_property SW EXPORT_OF ""
set_interface_property SW PORT_NAME_MAP ""
set_interface_property SW CMSIS_SVD_VARIABLES ""
set_interface_property SW SVD_ADDRESS_GROUP ""

add_interface_port SW SW sw Input 10

