# TCL File Generated by Component Editor 14.1
# Fri Jan 15 17:03:38 CET 2016
# DO NOT MODIFY


# 
# av2wb "av2wb" v1.0
#  2016.01.15.17:03:38
# 
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1


# 
# module av2wb
# 
set_module_property DESCRIPTION ""
set_module_property NAME av2wb
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME av2wb
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL av2wb
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file av2wb.sv SYSTEM_VERILOG PATH ./av2wb.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL av2wb
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file av2wb.sv SYSTEM_VERILOG PATH ./av2wb.sv


# 
# parameters
# 
add_parameter AW INTEGER 32
set_parameter_property AW DEFAULT_VALUE 32
set_parameter_property AW DISPLAY_NAME AW
set_parameter_property AW TYPE INTEGER
set_parameter_property AW UNITS None
set_parameter_property AW HDL_PARAMETER true
add_parameter DW INTEGER 64
set_parameter_property DW DEFAULT_VALUE 64
set_parameter_property DW DISPLAY_NAME DW
set_parameter_property DW TYPE INTEGER
set_parameter_property DW UNITS None
set_parameter_property DW HDL_PARAMETER true
add_parameter TW INTEGER 2
set_parameter_property TW DEFAULT_VALUE 2
set_parameter_property TW DISPLAY_NAME TW
set_parameter_property TW TYPE INTEGER
set_parameter_property TW UNITS None
set_parameter_property TW HDL_PARAMETER true
add_parameter MAX_OUTSTANDING INTEGER 2
set_parameter_property MAX_OUTSTANDING DEFAULT_VALUE 2
set_parameter_property MAX_OUTSTANDING DISPLAY_NAME MAX_OUTSTANDING
set_parameter_property MAX_OUTSTANDING TYPE INTEGER
set_parameter_property MAX_OUTSTANDING UNITS None
set_parameter_property MAX_OUTSTANDING HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 av_readdata readdata Output DW
add_interface_port avalon_slave_0 av_address address Input AW
add_interface_port avalon_slave_0 av_byteenable byteenable Input DW/8
add_interface_port avalon_slave_0 av_chipselect chipselect Input 1
add_interface_port avalon_slave_0 av_read read Input 1
add_interface_port avalon_slave_0 av_write write Input 1
add_interface_port avalon_slave_0 av_writedata writedata Input DW
add_interface_port avalon_slave_0 av_waitrequest waitrequest Output 1
add_interface_port avalon_slave_0 av_readdatavalid readdatavalid Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end wb_dat_i dat_i Input DW
add_interface_port conduit_end wb_rst_i rst_i Input 1
add_interface_port conduit_end wb_tgd_i tgd_i Input TW
add_interface_port conduit_end wb_dat_o dat_o Output DW
add_interface_port conduit_end wb_tgd_o tgd_o Output TW
add_interface_port conduit_end wb_ack ack Input 1
add_interface_port conduit_end wb_adr adr Output AW
add_interface_port conduit_end wb_cyc cyc Output 1
add_interface_port conduit_end wb_err err Input 1
add_interface_port conduit_end wb_lock lock Output 1
add_interface_port conduit_end wb_rty rty Input 1
add_interface_port conduit_end wb_sel sel Output DW/8
add_interface_port conduit_end wb_stb stb Output 1
add_interface_port conduit_end wb_tga tga Output TW
add_interface_port conduit_end wb_tgc tgc Output TW
add_interface_port conduit_end wb_we we Output 1

